# This file was generated by liblab | https://liblab.com/

from nhl_stats import NhlStats, Environment

sdk = NhlStats(base_url=Environment.DEFAULT.value)

result = sdk.miscellaneous.ping_server()

print(result)
